# Generated by Django 5.0.3 on 2024-03-13 07:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(max_length=255)),
                ('comment', models.TextField()),
            ],
            options={
                'verbose_name': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('body', models.TextField()),
            ],
            options={
                'verbose_name': ['subject'],
            },
        ),
        migrations.CreateModel(
            name='Mailout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField()),
                ('period', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=255)),
                ('clients', models.ManyToManyField(to='automatic_email.client')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='automatic_email.message')),
            ],
            options={
                'verbose_name': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Attempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('send_date', models.DateTimeField()),
                ('status', models.CharField(max_length=255)),
                ('response', models.TextField()),
                ('mailout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='automatic_email.mailout')),
            ],
            options={
                'verbose_name': ['-send_date'],
            },
        ),
    ]
